# Generated by Django 3.2 on 2021-08-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OficinaVirtualApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reclamo', models.CharField(max_length=10)),
                ('reclamo', models.TextField()),
                ('archivo1', models.ImageField(upload_to='reclamos')),
                ('archivo2', models.ImageField(upload_to='reclamos')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.suministro')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_novedad', models.DateTimeField()),
                ('area', models.CharField(max_length=10)),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(max_length=10)),
                ('reclamo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ReclamosApp.reclamos')),
            ],
        ),
    ]
