# Generated by Django 3.2 on 2021-08-08 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OficinaVirtualApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reclamo', models.CharField(choices=[('SER', 'Sin Servicio'), ('VAR', 'Variaciones de Tension'), ('PEL', 'Peligro Via Publica'), ('FAC', 'Error Facturacion'), ('DSC', 'Discrepancia Consumo'), ('PRE', 'Pago Repetido'), ('PVH', 'Pago a Valor Historico'), ('PNA', 'Pago no Acreditado'), ('RLQ', 'Reenvio Liquidacion'), ('LNR', 'Liquidacion No Recibida'), ('CPP', 'Consulta Planes de Pago')], max_length=3)),
                ('detalle', models.TextField()),
                ('alta', models.DateTimeField(auto_now_add=True)),
                ('imagen1', models.ImageField(upload_to='reclamos')),
                ('imagen2', models.ImageField(upload_to='reclamos')),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.suministro')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_novedad', models.DateTimeField(blank=True)),
                ('area', models.CharField(max_length=10)),
                ('observaciones', models.TextField()),
                ('estado', models.CharField(max_length=10)),
                ('reclamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReclamosApp.reclamos')),
            ],
        ),
    ]
