# Generated by Django 3.2 on 2021-08-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamos',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='reclamos'),
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='reclamos'),
        ),
    ]
