# Generated by Django 3.2 on 2021-08-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamos',
            old_name='reclamo',
            new_name='detalle',
        ),
        migrations.RenameField(
            model_name='reclamos',
            old_name='archivo1',
            new_name='imagen1',
        ),
        migrations.RenameField(
            model_name='reclamos',
            old_name='archivo2',
            new_name='imagen2',
        ),
        migrations.AddField(
            model_name='reclamos',
            name='alta',
            field=models.DateTimeField(auto_now_add=True, default='08/08/2021'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reclamos',
            name='tipo_reclamo',
            field=models.CharField(choices=[('SER', 'Sin Servicio'), ('VAR', 'Variaciones de Tension'), ('PEL', 'Peligro Via Publica'), ('FAC', 'Error Facturacion'), ('DSC', 'Discrepancia Consumo'), ('PRE', 'Pago Repetido'), ('PVH', 'Pago a Valor Historico'), ('PNA', 'Pago no Acreditado'), ('RLQ', 'Reenvio Liquidacion'), ('LNR', 'Liquidacion No Recibida'), ('CPP', 'Consulta Planes de Pago')], max_length=3),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reclamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ReclamosApp.reclamos'),
        ),
    ]
