# Generated by Django 3.2 on 2021-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReclamosApp', '0002_auto_20210808_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha_novedad',
            field=models.DateTimeField(blank=True),
        ),
    ]
