# Generated by Django 3.2 on 2021-07-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaVirtualApp', '0001_initial'),
        ('PagosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DebitoAutomatico',
            new_name='Debito_Automatico',
        ),
    ]
