# Generated by Django 3.2 on 2021-08-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OficinaVirtualApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('cuerpo', models.TextField()),
                ('publicacion', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='avisos')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('origen', models.CharField(max_length=20)),
                ('motivo', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.cliente')),
            ],
        ),
    ]
