# Generated by Django 3.2 on 2021-08-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvisosAlertasApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='imagen',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='publicacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
