# Generated by Django 3.2 on 2021-08-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AvisosAlertasApp', '0002_auto_20210803_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='imagen',
            field=models.ImageField(upload_to='avisos'),
        ),
    ]
