# Generated by Django 3.2 on 2021-07-30 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OficinaVirtualApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=30)),
                ('vencimiento', models.DateField()),
                ('importe', models.CharField(max_length=10)),
                ('factura', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.suministro')),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateField()),
                ('importe', models.CharField(max_length=10)),
                ('cuotas', models.IntegerField()),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.suministro')),
            ],
        ),
    ]
