# Generated by Django 3.2 on 2021-08-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaVirtualApp', '0005_remove_turno_cliente'),
        ('LiquidacionConveniosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convenio',
            name='suministro',
        ),
        migrations.AddField(
            model_name='convenio',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.cliente'),
        ),
        migrations.AddField(
            model_name='convenio',
            name='cuotas_pagadas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='convenio',
            name='estado',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='convenio',
            name='importe_cuota',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='convenio',
            name='prox_vencimiento',
            field=models.DateField(null=True),
        ),
    ]
