# Generated by Django 3.2 on 2021-08-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=40)),
                ('dni', models.IntegerField()),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('depto', models.CharField(blank=True, max_length=2, null=True)),
                ('barrio', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('factura', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20)),
                ('intentos', models.IntegerField()),
                ('caducidad', models.DateField()),
                ('avisos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('turno', models.DateTimeField()),
                ('motivo', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suministro', models.IntegerField()),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('depto', models.CharField(blank=True, max_length=2, null=True)),
                ('barrio', models.CharField(max_length=20)),
                ('tipo_consumo', models.CharField(max_length=20)),
                ('demanda', models.CharField(max_length=20)),
                ('estado', models.IntegerField()),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.cliente')),
            ],
        ),
    ]
