# Generated by Django 3.2 on 2021-07-21 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=30)),
                ('tipoDni', models.CharField(max_length=3)),
                ('dni', models.IntegerField()),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('depto', models.CharField(max_length=2)),
                ('barrio', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('factura', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=20)),
                ('intentos', models.IntegerField()),
                ('avisos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('motivo', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suministro', models.IntegerField()),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('piso', models.IntegerField()),
                ('depto', models.CharField(max_length=2)),
                ('barrio', models.CharField(max_length=20)),
                ('tipoConsumo', models.CharField(max_length=10)),
                ('demanda', models.CharField(max_length=20)),
                ('estado', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVencimiento', models.DateField()),
                ('fechaEmision', models.DateField()),
                ('importe', models.CharField(max_length=10)),
                ('fechaPago', models.DateField()),
                ('medioPago', models.CharField(max_length=10)),
                ('operacion', models.IntegerField()),
                ('estado', models.CharField(max_length=10)),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.suministro')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numFactura', models.CharField(max_length=20)),
                ('fechaVen', models.DateField()),
                ('importe', models.CharField(max_length=10)),
                ('fechaSeg', models.DateField()),
                ('importeSeg', models.CharField(max_length=20)),
                ('documento', models.BinaryField()),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.suministro')),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=30)),
                ('vencimiento', models.DateField()),
                ('importe', models.CharField(max_length=10)),
                ('factura', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.suministro')),
            ],
        ),
        migrations.CreateModel(
            name='DebitoAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta', models.CharField(max_length=20)),
                ('banco', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=80)),
                ('vencimiento', models.DateField()),
                ('estdado', models.CharField(max_length=20)),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.suministro')),
            ],
        ),
        migrations.CreateModel(
            name='Consumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaConsumo', models.DateField()),
                ('consumo', models.IntegerField()),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.suministro')),
            ],
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('origen', models.CharField(max_length=20)),
                ('motivo', models.CharField(max_length=20)),
                ('mensaje', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.cliente')),
            ],
        ),
    ]
