# Generated by Django 3.2 on 2021-08-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaVirtualApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministro',
            name='estado',
            field=models.CharField(max_length=15),
        ),
    ]
