# Generated by Django 3.2 on 2021-07-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaVirtualApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='tipoDni',
            new_name='tipo_dni',
        ),
        migrations.RenameField(
            model_name='consumos',
            old_name='fechaConsumo',
            new_name='fecha_consumo',
        ),
        migrations.RenameField(
            model_name='debitoautomatico',
            old_name='estdado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='fechaSeg',
            new_name='fecha_primer_ven',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='fechaVen',
            new_name='fecha_seg_ven',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='importe',
            new_name='imp_primer_ven',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='importeSeg',
            new_name='imp_seg_ven',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='numFactura',
            new_name='num_factura',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='fechaEmision',
            new_name='fecha_emision',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='fechaPago',
            new_name='fecha_pago',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='fechaVencimiento',
            new_name='fecha_vencimiento',
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='medioPago',
            new_name='medio_pago',
        ),
        migrations.RenameField(
            model_name='suministro',
            old_name='tipoConsumo',
            new_name='tipo_consumo',
        ),
    ]
