# Generated by Django 3.2 on 2021-07-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaVirtualApp', '0002_alter_suministro_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministro',
            name='tipo_consumo',
            field=models.CharField(max_length=20),
        ),
    ]
