# Generated by Django 3.2 on 2021-08-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaVirtualApp', '0002_alter_suministro_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suministro',
            name='demanda',
            field=models.CharField(choices=[('PEQ', 'Pequeña'), ('MED', 'Mediana'), ('GRD', 'Grandes'), ('TRP', 'Trifasico Pequeña'), ('TRM', 'Trifasico Mediana'), ('TRG', 'Trifasico Grandes'), ('TRI', 'Industriales')], max_length=3),
        ),
        migrations.AlterField(
            model_name='suministro',
            name='tipo_consumo',
            field=models.CharField(choices=[('RES', 'Residencial'), ('RUL', 'Rural'), ('COM', 'Comercial'), ('PYM', 'Pymes'), ('IND', 'Industria')], max_length=3),
        ),
    ]
