# Generated by Django 3.2 on 2021-08-01 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaVirtualApp', '0003_alter_suministro_tipo_consumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('turno', models.DateTimeField()),
                ('motivo', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Turnos',
        ),
    ]
