# Generated by Django 3.2 on 2021-08-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OficinaVirtualApp', '0004_auto_20210801_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='cliente',
        ),
    ]
