# Generated by Django 3.2 on 2021-08-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OficinaVirtualApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_documento', models.CharField(max_length=20)),
                ('vencimiento_pri', models.DateField()),
                ('importe_pri', models.CharField(max_length=10)),
                ('vencimiento_seg', models.DateField()),
                ('importe_seg', models.CharField(max_length=20)),
                ('documento', models.BinaryField()),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.suministro')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('consumo', models.IntegerField()),
                ('suministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OficinaVirtualApp.suministro')),
            ],
        ),
    ]
